name: CI

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: |
          yarn install
          yarn lint
          yarn test
          yarn build
          yarn export
      - name: Deploy
        uses: docker://peaceiris/gh-pages:v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_PAT }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./out
